### PR TITLE
Fix fog render and add configuration

### PR DESCRIPTION
**Pull request by jaquadro**
This fixes an oversight I made when moving the near-plane distance closer to enhance dense fog biomes, causing haziness in biomes which shouldn't have closer fog.

This sets the near plane distance between 0.1 and 0.75 (vanilla) of the far plane distance based on the 0.0 - 1.0 fog density of the biome.

I also added two boolean config properties to toggle the fog color and density, since the restoration of this feature may not be welcome by all players or packs.

### CODE REVIEW

**Comment by Adubbz** [comment]
The trouble with a config option for fog density is that it creates an uneven playing field amongst players who do and don't have it enabled. The original intention was to reduce the visibility of the player in certain biomes so they're more prone for attack (as well of course the added visuals really help set the biome's tone too).

Everything else is fine though, including the config option for fog colour.

**Comment by jaquadro** [comment]
Fair point, I only looked at it from an atmospheric perspective.

I think there's still merit to the entry, but for balance reasons it would need to be forced down by the server, and that's a bit more complexity.  I've updated the PR without that entry.

**Comment by TDWPFTW** [comment]
I've noticed a small problem with the fog rendering.  It doesn't seem to take the water fog into account.

This is what it looks like underwater in a biome without any fog coloring: http://i.imgur.com/LB6xGKG.png

And this is what it looks like in the Seasonal Forest (Which has an orange fog): http://i.imgur.com/dP0cn96.png

**Comment by jaquadro** [comment]
Ah, I know what's missing.  So I have a question then: should all water present the standard blue shade, or should it take the biome's water color into account?

**Comment by TDWPFTW** [comment]
didn't even think about that, but that'd be even better.

**Pull request merged**
