### PR TITLE
Smooth fog color and distance rendering

### PR DESCRIPTION
**Pull request by jaquadro**
This re-enables fog color and distance rendering.

The fog can be made much smoother by interpolating the edge squares based on the player's position within its current square.  Both fog color and fog distance are greatly smoothed out this way.

Should resolve the concerns in #251 .

### CODE REVIEW

**Comment by Adubbz** [comment]
There's two aspects to fog colouring/distances which i'd be curious to see before pulling this:

* Does the fog appear overly bright during the night? 
* For biomes without an altered fog distance, or those using a 'default' value, do they match up to Vanilla on the same settings?
* Is the transitioning smooth? (Which this commit addresses)

I ask because I can't recall how things were left with regards to the two features, been quite a while since I touched fog. I do however remember these were issues in the past so it'd be good to know for sure.

And of course, a preview of the transition in the form of a gif or video would be great.

**Comment by jaquadro** [comment]
Well for something like this I figured you would pull the branch down separately and test.  Since as you say it's something that's been left untouched for the last 8 months.  But I could try to record something later.

* I don't think the fog was bright at night, but I'd need to check again.  I'm pretty sure I kept forcing daylight because everything at night is .. well, really dark.
* It looked unchanged to me.  While walking away from the ominous woods, the render distance extends out quite far and the fog color returns to a bright pale blue.
* The transitioning looks quite smooth now.  I ran the fog as it was left in July and saw just how choppy the stepping was.  The difference is night and day.

What biomes besides Ominous Woods add fog?  One thing I did notice is that I was getting a grey fog (which for that biome looked fine), but that differed from the more murky purple I saw on the wiki.

**Comment by jaquadro** [comment]
Finally got a chance to investigate those points.

* Turns out the fog still has its daylight brightness at night, though this only impacts the special fog biome.  I think some of the default fog code could be adapted to scale this down depending on time of day.
* There is a barely perceptible change between vanilla and fog processing on a fogless biome.  This is probably precision loss while interpolating some of the RGB byte values.  Switching the process to floating point RGB components would probably eliminate the slight difference.

Now there's one major problem I did not notice, since I was focusing on the ominous woods.  I saw that about a dozen biomes have fogs, most of them with density values close to zero.  The density value is being taken as the farPlaneDistance, which I assume was not the intention.  It makes the blocks in a Temperate Rainforest invisible even if they're right in front of you, for example.

I'm interested enough in getting the fog code working properly to keep chewing on this, but I'd like some guidance on how the density values in the fog interface should actually be interpreted.

**Comment by jaquadro** [comment]
I pushed a couple more changesets to the PR, to fix the color under different light conditions, make the interpolation more precise, and give the fog a little more 'depth'.

I've recorded a short demonstration: http://www.twitch.tv/texelsaur/b/639067740
Hopefully that works okay, first time using Twitch.

I saw in the history that Ominous Woods had its fog density changed to a far plane distance instead, and I assume the rest of the biomes would need to be updated with something reasonable.

**Comment by Adubbz** [comment]
Yup, that looks absolutely perfect.

With regards to the density values, if I recall correctly, they were based on the maximum possible fog distance. The minimum of the current fog distance and the biome's density value (taking into account position) was used.

If you want to change all of the values to something more standardized/logical go right ahead (0.0 to 1.0 perhaps?), i'm happy to merge this based on looking at both the code and the video.

**Comment by jaquadro** [comment]
So if I understand that correctly, the previous interpretation of density was a value of 0 represented no visibility, and a value of 1 represented maximum view distance?  I scribbled down what all the biomes are currently set to:

Artctic - 0.4
Bamboo Forest - 0.01
Bayou - 0.6
Crag - 1.0
Dead Swamp - 0.6
Fen - 0.8
Frost Forest - 0.6
Mystic Grove - 1.0
Ominous Woods - 0.1
Polar Chasm - 0.01
Seasonal Forest - 1.0
Sludge Pit - 0.6
Temperate Rainforest - 0.8
Tropical Rainforest - 0.01
Wasteland - 0.3

What sticks out to me is bamboo forest, polar chasm, and tropical rainforest.  I'm not sure if those values were intentional.

It would be a simple change to just stick with those values and calculate the far plane distance from a constant (240 being max view distance, 160 being default view distance, 100 based on your ominous woods value conversion).

I can put something in tomorrow so you won't be pulling something that will effectively break biomes.  But feel free to pull it now if you want to go through and tweak the values anyway.

**Comment by Adubbz** [comment]
Having a look at past commits, the original interpretation was 0.0 for no visibility and 1.0 for maximum view distance, but then I changed it to be 0 for no visibility and 240 for max visibility (which was a bit of a silly move, but no matter).

But yeah, i'll pull this now and do the same for any default values too. Forstride said he'd have a play with them too, but until he gets around to doing that, doing as you said would be great.

**Comment by Adubbz** [comment]
Never actually got around to saying it, but thanks for this too man. It's great to see changes like this pop up, especially since i'd probably have never gotten to it myself otherwise. Don't mind the mess that is the majority of the BoP 1.7 codebase though :P

**Pull request merged**
