### PR TITLE
Add Gem Blocks to OreDictionary and change Gem Recipes to use OreDict…

### LINKED ISSUE #1287: [1.12.2] [suggestion] gemBlock OreDict
Please Register the "gemBlocks"(Ruby Block, Amethyst Block, e.t.c) to the OreDictionary to make them useable for other mods Recipes.(For Example Ruby Block with OreDictionary:blockRuby)

### LINKED ISSUE #1300: Register Biomes O' Plenty gem blocks in Ore Dictionary
Can you register the gem blocks in the ore dictionary? (like the Block of Peridot). An example entry would be "blockPeridot." This would be useful for users of [JAOPCA](https://minecraft.curseforge.com/projects/jaopca), which per default registers new blocks with BOP (although I have personally disabled this).

### PR DESCRIPTION
**Pull request by ToMe25**
…ionary.
Closes #1287 and Closes #1300.

### CODE REVIEW

**Comment by Forstride** [comment]
Closing this because we either can't/won't fix it or it's not an issue in 1.13

**Comment by ToMe25** [comment]
@Forstride why closing this? its a 1.12.2 issue right but BoP got 1.12.2 updates after i opened this.
Doesn't it work just like it was?

**Comment by Forstride** [comment]
Oh whoops, didn't mean to close this.

**Comment by ToMe25** [comment]
Thank you :)

**Pull request merged**
