### PR TITLE
Update es_es.json

### PR DESCRIPTION
**Pull request by zeedif**

### CODE REVIEW

**Comment by Forstride** [comment]
Just a heads up, the mod name/abbreviation probably shouldn't be translated.  No other localizations for BOP do it, and AFAIK even Minecraft's own localizations don't translate the name of the game.  The music disc track shouldn't be translated either, since that's obviously the name of an actual song.

**Comment by zeedif** [comment]
Well, you can make changes to my translation. I had only come up with that clever translation for the name that I thought sounded funny. Please edit the pull before approving it or upload a commit afterwards. And I'm sorry, I didn't catch the song title, and I like to translate all the lines as long as the term isn't made up.

**Comment by zeedif** [comment]
I would like it to be translated for the achievement, but in the end, you are the authors and you decide how you prefer the translation.

**Comment by Forstride** [comment]
If you mean the Wanderer achievement, that's fine, I just don't want the music disc description translated since they're proper names.  And yeah I'd prefer the mod name not be translated anywhere since the English name is the only name we use on our official outlets.

Also if you want to make the changes yourself I can just wait to merge the PR.

**Comment by Forstride** [comment]
You missed the first one for the root advancement :P

**Pull request merged**
