### PR TITLE
Initial Thaumcraft integration

### PR DESCRIPTION
**Pull request by Adaptivity**
Notes:
1) Some 1.7 blocks still have no aspect support (Will add them later)
2) Golems support wasn't tested but should work.

### CODE REVIEW

**Comment by Adaptivity** [comment]
@Adubbz just finished ForgeMultipart integration. Will PR it next when this PR gets merged.

**Comment by Adubbz** [comment]
Looks good. Can't really say whether or not it's balanced since it's been a long time since i've played TC (Even got a tweet about my failings at it recently :P)

**Comment by Adubbz** [comment]
Oh, let me know when you've finished up with this too, since I might as well port this over to 1.8 since all of the blocks and items are essentially finished

**Comment by Bogdan-G** [comment]
See that it does not cause even more checks and backlog, through interaction with TC API is not very fast by itself.

**Pull request merged**
