### PR TITLE
Config to Enable or Disable BoP Ores

### PR DESCRIPTION
**Pull request by fewizz**

### CODE REVIEW

**Comment by Dream-Master** [comment]
@Adubbz can add this to BOP because disable ores is very helpfull.

**Comment by Adaptivity** [comment]
@cheeserolls can do this too :smile:

**Comment by Dream-Master** [comment]
Ok.

**Comment by Adubbz** [comment]
Bah, must've missed this one when I was fixing my emails. Happy to merge this as a temporary measure for 1.7, in 1.8 this option has already been provided (albeit in a different manner).

**Comment by Dream-Master** [comment]
cool thanks

**Comment by cheeserolls** [comment]
@Adaptivity Yeah, I could, but I wasn't sure if @Adubbz was going to want to.  As he said, it's a temporary measure for 1.7 which is approaching end-of-life anyway.  In the 1.8 version we're doing config differently (and LOADS of stuff will be configurable).

**Comment by Dream-Master** [comment]
Have a config is better in any way because most Players play Mod Packs and for better Tiering you can switch on and off Ores/Gems you want.

**Pull request merged**
