### PR TITLE
Add woodcutting recipes

### PR DESCRIPTION
**Pull request by NemoNotFound**
I added woodcutting recipes from Nemo's Woodcutter for all wood types. 
They were added for each mod loader, since each has it's own way to add conditions.
The conditions are necessary to avoid log spamming, if Nemo's Woodcutter is not loaded.

Related to this [suggestion](https://github.com/Glitchfiend/BiomesOPlenty/issues/2277)

### CODE REVIEW

**Comment by Forstride** [comment]
Yeaaaaah, that's a lot more than I expected.  And if the recipe/advancement format changes at some point (Which is extremely likely knowing Mojang), we'd probably just end up gutting the whole thing.

Honestly, why not just condense all mod compat stuff into a separate mod?  That way there's no need to worry about checking if the mod is loaded or not, plus you'd get extra CF/Modrinth revenue lol

**Comment by NemoNotFound** [comment]
Yeah, when I saw how many files were generated, I also thought it's too much. I'll probably do an add-on mod for Biomes O' Plenty.

Is it fine for you if I call it Nemo's Woodcutter (Biomes O' Plenty) Add-On?
And also are there plans for wood types in the future?

**Comment by Forstride** [comment]
Yeah I don't mind the name.  As for future wood types, right now I don't have any plans, but it's always possible that'll change.

**Comment by NemoNotFound** [comment]
Okay, thank you!

**Pull request closed without merging**
