### PR TITLE
fix custom boats

### PR DESCRIPTION
**Pull request by Corail31**

### CODE REVIEW

**Comment by Corail31** [comment]
fix-boat

**Comment by Forstride** [comment]
god bless you

**Comment by Forstride** [comment]
ehm...there seems to be a big problem.  you can't actually row them for some reason...

**Comment by Corail31** [comment]
yes but you send the vanilla packet CSteerBoatPacket in the code that checks for a BoatEntity in ServerPlayNetHandler, i only fixed the spawn. (i saw i also added an import that is not in the api)
```
   public void processSteerBoat(CSteerBoatPacket packetIn) {
      PacketThreadUtil.checkThreadAndEnqueue(packetIn, this, this.player.getServerWorld());
      Entity entity = this.player.getRidingEntity();
      if (entity instanceof BoatEntity) {
         ((BoatEntity)entity).setPaddleState(packetIn.getLeft(), packetIn.getRight());
      }
   }
```

**Comment by Corail31** [comment]
```java
   public void updateRidden() {
      super.updateRidden();
      this.rowingBoat = false;
      if (this.getRidingEntity() instanceof BoatEntity) {
         BoatEntity boatentity = (BoatEntity)this.getRidingEntity();
         boatentity.updateInputs(this.movementInput.leftKeyDown, this.movementInput.rightKeyDown, this.movementInput.forwardKeyDown, this.movementInput.backKeyDown);
         this.rowingBoat |= this.movementInput.leftKeyDown || this.movementInput.rightKeyDown || this.movementInput.forwardKeyDown || this.movementInput.backKeyDown;
      }

   }
```
I think that the inputs that are used in the method controlBoat() are normally updated in the ClientPlayerEntity and also change the rowingBoat. (and for entityBoat)
You can debug control boat to see this (and you can put values in to see the boat moving)

**Pull request merged**
