### PR TITLE
Fixed rare crash, BetterFoliage support

### LINKED ISSUE #515: 1.7.10: Crash when loading an existing world
Hi,
I'm getting this crash when I try to load an existing world.
First it warns about a possible corruption and after a world backup it crashes.
http://pastebin.com/TFgbyC8F
Maybe you have an idea why this happens.
I tried different versions for 1.7.10 including the newest build 1364.

### LINKED ISSUE #558: [1.7.10] Server crash
I was told by the dev of Forge Essentials to post this issue here.

https://github.com/ForgeEssentials/ForgeEssentials/issues/1875

### PR DESCRIPTION
**Pull request by Adaptivity**
re-pull of #586
@Adubbz should be good now? BetterFoliage is BetterGrassAndLeavesMod replacement for 1.7.10.
close #515
close #558

### CODE REVIEW

**Comment by Adubbz** [comment]
Change != Blocks.air to != null and it should be good to go. The game seems a bit weird about how it handles air, but more often than not it involves the use of null. Since the issue is a NullPointerException I think that's the case needing to be handled. Sorry for not being more specific about this in my last comment

**Comment by Adaptivity** [comment]
Changed :+1:

**Comment by Adubbz** [comment]
Merged :)

**Comment by Bogdan-G** [comment]
less than NPE, the better! :)

**Pull request merged**
