### PR TITLE
Add mushroom tags

### PR DESCRIPTION
**Pull request by cech12**
This PR adds mushroom tags for a better mod compatibility. 

I am the developer of the mod [Extended Mushrooms](https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms), where I add some new mushrooms and mushroom related wood types (and much more). With these tags I am able to use your mushrooms in my mod.

I also opened a PR in MinecraftForge to add these tags: https://github.com/MinecraftForge/MinecraftForge/pull/6620

### CODE REVIEW

**Comment by Forstride** [comment]
I'll wait and see what Forge does with the PR you submitted to them before merging

**Comment by cech12** [comment]
Okay :) But the mod compatibility will also work unrelated to the PR at Forge. ;)

**Comment by Forstride** [comment]
Yes but you could also just do that within your own mod AFAIK.  I'm not entirely sure how loading tags works if a mod isn't installed, like if it fails to load the entire file like models/blockstates do, but you could try it.

**Comment by cech12** [comment]
That was my first step. But referencing items of not loaded mods inside a tag file will break it. :/

Hardcoding your blocks and items via reading them from registry could also be a solution, but that is not that flexible.

Another solution could be, if you add some tags for your mushrooms inside the mod tags. So, I can add it as an empty tag and can reference it. But the problem is, that there is no tag for your mushroom blocks and items. A difference between mushrooms, stems and caps is needed. :)

**Comment by MarioSMB** [comment]
I see this has been opened for 3 years so apologies for a late bit of feedback (assuming this is still relevant):  
Items from unloaded mods can indeed be referenced in tags, you just have to make sure they're set as not required, e.g. `{"id":"modname:mod_item","required":false}`.  

Compatibility is in a funky situation when it comes to cross-mod features and sadly it looks like Forge didn't do much with it (stale bots auto-closing PRs - sheesh!). Hope that tag tip helps at least!

**Comment by cech12** [comment]
Thanks for your response. I don't know if this worked 3 years ago xD But you are right, this should work now. :)
Forge did not accept the tag additions about mushrooms but other mods like Quark did. So, maybe you can also think about adding these tags to add our own standard of mushroom tags which maybe other mods will follow :)

**Comment by Forstride** [comment]
Probably not gonna add the tags since there's really no need, and nothing in our mod would use them.

**Pull request closed without merging**
