### PR TITLE
Add BOP Blocks/Items to the Vanilla Creative tabs

### PR DESCRIPTION
**Pull request by JT122406**
PR follows the same style as Vanilla and includes the BOP blocks in with them in the correct tabs and next to the correct items that they should be next to using Forge's CreativeModeTabEvent.BuildContents event to do so.
I am open to suggestions to add more things in x tab.
I was also debating making this disable able in the config but since the config is world gen and not general I decided not to but would still be open to this idea
Screenshot (139)

### CODE REVIEW

**Comment by Forstride** [comment]
Absolutely not.  We have our own Creative tab for a reason...

**Comment by JT122406** [comment]
> Absolutely not. We have our own Creative tab for a reason...

Why do you think I said it should be a config option

**Comment by JT122406** [comment]
Also at least besides just closing and calling done we can have an open conversation about it and the possibilities as that is how open source is supposed to work and if you don't want to do that what is the point of being open source @Forstride

**Comment by JT122406** [comment]
Also this feature is one a lot of people who are creative building enjoy as they can see all of for example the wood blocks in one area instead of having to flip between different specific tabs or search you can see all of the options to choose what best fits the need of that builder

**Comment by Forstride** [comment]
The mod isn't "open" source.  It's visible source.  And I don't have to entertain ideas and go into specifics on why I don't want something.

**Comment by JT122406** [comment]
> The mod isn't "open" source. It's visible source. And I don't have to entertain ideas and go into specifics on why I don't want something.

I would love for you to go into specifics on why you don’t want something that people do want

**Comment by JT122406** [comment]
> The mod isn't "open" source. It's visible source. And I don't have to entertain ideas and go into specifics on why I don't want something.

Also if it’s “visible source” and not “open source” you should have forking turned off as allowing forking is the way of saying hey we are open source and are looking for contributions

**Comment by Forstride** [comment]
We do accept contributions, but generally only localizations, and the occasional bugfix/optimization.  Content/design-centric PRs are pretty much never gonna be accepted.

Also in this specific case, this is something that's been a conscious design choice of the mod for basically as long as it's been around.  Aside from the fact that it's already extremely niche for people to play Creative with mods, I don't want our items cluttering the vanilla tabs, which would probably annoy people more than it would help them.

And for what it's worth, I've never seen a single person ever ask for this, aside from you.

**Comment by JT122406** [comment]
> We do accept contributions, but generally only localizations, and the occasional bugfix/optimization. Content/design-centric PRs are pretty much never gonna be accepted.
> 
> Also in this specific case, this is something that's been a conscious design choice of the mod for basically as long as it's been around. Aside from the fact that it's already extremely niche for people to play Creative with mods, I don't want our items cluttering the vanilla tabs, which would probably annoy people more than it would help them.
> 
> And for what it's worth, I've never seen a single person ever ask for this, aside from you.

I have builders for the mod I work on and server builders who ask for this so

**Pull request closed without merging**
