### PR TITLE
Fixed compostable items for neoforge

### PR DESCRIPTION
**Pull request by StupidRepo**
gif lol
another gif lol

### CODE REVIEW

**Review by JT122406 — APPROVED** [review]
Only thing I can think is they might want this done via Datagen as BOP has NeoForge Datagen setup

**Comment by Adubbz** [comment]
Correct, data gen would be preferred here

**Comment by StupidRepo** [comment]
👍🏽 Alright, I'm currently replying from school so I'll take a look at getting this implemented after school. I would prefer to implement this into Glitchcore's compostable function itself but I feel that may be extra effort. I'll still try regardless :)

**Comment by JT122406** [comment]
> 👍🏽 Alright, I'm currently replying from school so I'll take a look at getting this implemented after school. I would prefer to implement this into Glitchcore's compostable function itself but I feel that may be extra effort. I'll still try regardless :)

This wouldn’t be possible as it wouldn’t have access to the items from bop and it can’t be a method like it currently is as it is json based

**Comment by StupidRepo** [comment]
Oh yeah true...

**Comment by StupidRepo** [comment]
Will get around doing this sometime during the week or on the weekend. 👍🏽

**Comment by StupidRepo** [comment]
I had to switch to building this on Mac, as I was having some troubles on building on Ubuntu. Now, I'm having even more issues. Won't be able to complete this today, I'll have to try again tomorrow.

<details><summary>Mac Issues</summary>
<p>
image


Why did NeoForge decide to be slightly special and change something that (from as far as I can see) has been working just fine? 😭 
</p>
</details>

**Comment by StupidRepo** [comment]
So sorry for the incredibly stupid commit titles, if you want me to fork again and add the changes without the extra commits, let me know and I'll do that 👍🏽 

Effectively, to register something as compostable, just do the normal `registerCompostable` in `ModVanillaCompat.java`, and then run `dataGen` and it'll do magical things which I think can be improved and then it'll work :)

Actually, I will just re-make this whole PR as it's very annoying how stupid I've made it. And I wouldn't like this going on BOP's commit history forever...

**Pull request closed without merging**
