### PR TITLE
Added Polish translation (Made by @EliogabalusPL)

### PR DESCRIPTION
**Pull request by GirafiStudios**
Translation file made by @EliogabalusPL and linked in https://github.com/Glitchfiend/BiomesOPlenty/issues/1117
Figured I would make the PR, since he/she couldn't figure out how to do it.

### CODE REVIEW

**Comment by EliogabalusPL** [comment]
THX

**Comment by srs-bsns** [comment]
BoP is still using `"pack_format": 2`, so the filename should still have uppercase in it's name: `pl_PL.lang`.

**Comment by GirafiStudios** [comment]
You are indeed right @srs-bsns, didn't notice - just copied the file he linked in his post.
The file actually contained Bibliocraft, but I found the right translation on his fork.
Should be all good now.

**Comment by srs-bsns** [comment]
@GirafiStudios
In your latest commit I can see the updated data, but the filename is still listed as lower case. Due to the case-insensitivity of Git, you will likely need to use `git mv` for the filename change to be recognized.

**Comment by EliogabalusPL** [comment]
I wrote that when I add myself, I mess it up.

**Comment by GirafiStudios** [comment]
Well did it manually.
Thank god you can squash commits when accepting a PR nowadays.

**Comment by EliogabalusPL** [comment]
EMBARRASSED :(

**Pull request merged**
