### PR TITLE
Fix for Issue #760 - Turkish Locale Bug

### PR DESCRIPTION
**Pull request by lazerzes**
Sets the Default Locale to English. Fixes Issue #760

### CODE REVIEW

**Comment by Adubbz** [comment]
My concern here is whether this has any side-effects, breaking other things. Are you certain this is not the case here?

**Comment by lazerzes** [comment]
@Adubbz it does not appear to break other things, we may want to do more testing with it or possibly do an if statement to see if the machine is running in Turkish and set the Locale to English.

Either way, I built my fix and had it tested on a Turkish computer and it was able to run with the fix. I will push it to the 1.9.4 as soon as I can.

**Comment by Adubbz** [comment]
I guess there's no harm in merging this for now, if any troubles come as a result it's a relatively simple thing to change back

**Comment by lazerzes** [comment]
Alright! If you need me to improve the fix, just give me a poke! 

Have a nice day!

**Pull request merged**
