### PR TITLE
WIP: Update Forge and MCP Mappings Version

### PR DESCRIPTION
**Pull request by CDAGaming**
(This PR also contains other Code Cleanup)

Why the WIP Tag:
Since `func_192633_a` was changed to it's equivalent function in the new mappings, `updatePosition` as well as an Override removed (Line 271-272) due to 2 build errors, the following areas need additional testing to ensure what it controls still functions: `/src/main/java/biomesoplenty/client/gui/GuiBOPPageList.java`

### CODE REVIEW

**Comment by CDAGaming** [comment]
Typo in Title, fixed.

**Comment by GirafiStudios** [comment]
I can pretty much assure you that this won't get accepted (I have done PRs to BoP before)
Only updating the mappings, and no cleanup, might be nice though! ^^

**Comment by Adubbz** [comment]
Yeah, I do agree that it would be better to split this up into a mappings update and a 'cleanup' rather than mixing them together. Some of the changes are also probably more so stylistic than cleanup (e.g. public on interfaces), but I'm not necessarily opposed to them either, provided they are seperated

**Comment by CDAGaming** [comment]
Ok, I can separate this into 2 PRs: One with the MCP and Forge Updates, and One for the Code Cleanup

Will most likely have to do this sometime tomorrow but ill tag the 2nd PR once made.

**Comment by CDAGaming** [comment]
To-Do

- [ ] Update Forge and MCP Mappings Again (Forge has made a lot of changes today)
- [ ] Revert Code Cleanup (And Put into another PR in the near future)

**Comment by CDAGaming** [comment]
PR has now been split up, Will post the Cleanup PR once this is merged :)

**Comment by CDAGaming** [comment]
👍 CleanUp PR will be posted tomorrow morning

**Pull request merged**
