### PR TITLE
Terrarium assets edit: Significantly less textures

### PR DESCRIPTION
**Pull request by Nazenn**
The end result of these edits to the mesh and textures is that the total texture amount for all the terrariums goes down to 25 instead of the 75 that were originally being used. It could be reduced to 22 if further edits were made to the jar itself, but I didn't feel those edits for three less textures we worth the more significant changes that would have to be done. 

First time using github for anything more then filing an issue, I learnt about branches and pull requests from doing this so please let me know if I did anything wrong at all. I'm sure I probably didn't do it very efficiently but as long as its done right I'll be happy.

If 1.10.2 is still being updated I can also file a PR for that as well so it also gets these edits.

### CODE REVIEW

**Comment by Adubbz** [comment]
Could you please resubmit this with all of these changes merged into one commit? Google Git squashing for reference

**Comment by srs-bsns** [comment]
You can squash on merge. See the merging drop-down. :)

**Comment by Adubbz** [comment]
Yeah, however Forstride already merged the PR earlier and forgot to do that so I had to roll the repo back (there's like 80 commits... This is why the Github editor is bad kids!)

**Comment by Forstride** [comment]
Yeah, I didn't realize it would actually add all of those commits to the repo :P

**Pull request merged**
